// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyVera.Infrastructure.Persistence;

#nullable disable

namespace StudyVera.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522080413__init")]
    partial class _init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudyVera.Application.Dtos.ProfileSummary.UserRankResult", b =>
                {
                    b.Property<int>("UserRank")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kamu Personeli Seçme Sınavı",
                            ExamDate = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KPSS"
                        });
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("RequestorId", "ReceiverId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("c4a760a8-5b3d-4d3b-9a9f-1f1e4f1e4f1e"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetExam")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("ExamQuestionCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamId = 1,
                            ExamQuestionCount = 30,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            ExamId = 1,
                            ExamQuestionCount = 27,
                            Name = "Matematik"
                        },
                        new
                        {
                            Id = 3,
                            ExamId = 1,
                            ExamQuestionCount = 3,
                            Name = "Geometri"
                        },
                        new
                        {
                            Id = 4,
                            ExamId = 1,
                            ExamQuestionCount = 27,
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = 5,
                            ExamId = 1,
                            ExamQuestionCount = 18,
                            Name = "Çoğrafya"
                        },
                        new
                        {
                            Id = 6,
                            ExamId = 1,
                            ExamQuestionCount = 9,
                            Name = "Vatandaşlık"
                        },
                        new
                        {
                            Id = 7,
                            ExamId = 1,
                            ExamQuestionCount = 6,
                            Name = "Güncel Olaylar"
                        });
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.LessonSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("LessonSchedules");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Mock.UserMockExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmpty")
                        .HasColumnType("int");

                    b.Property<double>("TotalNet")
                        .HasColumnType("float");

                    b.Property<int>("TotalWrong")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMockExams");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Mock.UserMockExamDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("EmptyCount")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("UserMockExamId")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserMockExamId");

                    b.ToTable("UserMockExamDetails");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.ProfileStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileStats");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.QuestionStatDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("int");

                    b.Property<int>("UserQuestionStatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserQuestionStatId");

                    b.ToTable("QuestionStatDetails");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LessonId = 2,
                            Name = "İşlem Yeteneği",
                            OrderIndex = 1,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 2,
                            LessonId = 2,
                            Name = "Temel Kavramlar",
                            OrderIndex = 2,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 3,
                            LessonId = 2,
                            Name = "Tek - Çift - Pozitif - Negatif Sayılar",
                            OrderIndex = 3,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 4,
                            LessonId = 2,
                            Name = "Ardışık Sayılar",
                            OrderIndex = 4,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 5,
                            LessonId = 2,
                            Name = "Faktöriyel",
                            OrderIndex = 5,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 6,
                            LessonId = 2,
                            Name = "Sayı Basamakları ve Taban Aritmetiği",
                            OrderIndex = 6,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 7,
                            LessonId = 2,
                            Name = "Bölme - Bölünebilme",
                            OrderIndex = 7,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 8,
                            LessonId = 2,
                            Name = "Asal Çarpanlara Ayırma",
                            OrderIndex = 8,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 9,
                            LessonId = 2,
                            Name = "EBOB - EKOK",
                            OrderIndex = 9,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 10,
                            LessonId = 2,
                            Name = "Rasyonel Sayılar",
                            OrderIndex = 10,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 11,
                            LessonId = 2,
                            Name = "Basit Eşitsizlikler",
                            OrderIndex = 11,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 12,
                            LessonId = 2,
                            Name = "Mutlak Değer",
                            OrderIndex = 12,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 13,
                            LessonId = 2,
                            Name = "Üslü Sayılar",
                            OrderIndex = 13,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 14,
                            LessonId = 2,
                            Name = "Köklü Sayılar",
                            OrderIndex = 14,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 15,
                            LessonId = 2,
                            Name = "Çarpanlara Ayırma",
                            OrderIndex = 15,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 16,
                            LessonId = 2,
                            Name = "Oran - Orantı",
                            OrderIndex = 16,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 17,
                            LessonId = 2,
                            Name = "Birinci Dereceden Denklemler",
                            OrderIndex = 17,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 18,
                            LessonId = 2,
                            Name = "Sayı Problemleri",
                            OrderIndex = 18,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 19,
                            LessonId = 2,
                            Name = "Kesir Problemleri",
                            OrderIndex = 19,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 20,
                            LessonId = 2,
                            Name = "Yaş Problemleri",
                            OrderIndex = 20,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 21,
                            LessonId = 2,
                            Name = "Hareket Problemleri",
                            OrderIndex = 21,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 22,
                            LessonId = 2,
                            Name = "İşçi - Havuz Problemleri",
                            OrderIndex = 22,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 23,
                            LessonId = 2,
                            Name = "Yüzde - Kâr - Zarar - Faiz Problemleri",
                            OrderIndex = 23,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 24,
                            LessonId = 2,
                            Name = "Karışım Problemleri",
                            OrderIndex = 24,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 25,
                            LessonId = 2,
                            Name = "Grafik Problemleri",
                            OrderIndex = 25,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 26,
                            LessonId = 2,
                            Name = "Kümeler",
                            OrderIndex = 26,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 27,
                            LessonId = 2,
                            Name = "İşlem - Modüler Aritmetik",
                            OrderIndex = 27,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 28,
                            LessonId = 2,
                            Name = "Permütasyon - Kombinasyon - Olasılık",
                            OrderIndex = 28,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 29,
                            LessonId = 2,
                            Name = "Fonksiyonlar",
                            OrderIndex = 29,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 30,
                            LessonId = 2,
                            Name = "Sayısal Mantık",
                            OrderIndex = 30,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 31,
                            LessonId = 3,
                            Name = "Üçgenler",
                            OrderIndex = 1,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 32,
                            LessonId = 3,
                            Name = "Çokgenler - Dörtgenler",
                            OrderIndex = 2,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 33,
                            LessonId = 3,
                            Name = "Çember - Daire",
                            OrderIndex = 3,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 34,
                            LessonId = 3,
                            Name = "Katı Cisimler",
                            OrderIndex = 4,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 35,
                            LessonId = 3,
                            Name = "Analitik Geometri",
                            OrderIndex = 5,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 36,
                            LessonId = 4,
                            Name = "İslamiyet Öncesi Türk Tarihi",
                            OrderIndex = 1,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 37,
                            LessonId = 4,
                            Name = "İlk Türk - İslam Devletleri",
                            OrderIndex = 2,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 38,
                            LessonId = 4,
                            Name = "Anadolu (Türkiye) Selçuklu Devleti",
                            OrderIndex = 3,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 39,
                            LessonId = 4,
                            Name = "Osmanlı Devleti Kültür ve Medeniyeti",
                            OrderIndex = 4,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 40,
                            LessonId = 4,
                            Name = "Osmanlı Devleti Kuruluş Dönemi (1299 - 1453)",
                            OrderIndex = 5,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 41,
                            LessonId = 4,
                            Name = "Osmanlı Devleti Yükselme Dönemi (1453 - 1595)",
                            OrderIndex = 6,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 42,
                            LessonId = 4,
                            Name = "XVII. Yüzyılda Osmanlı Devleti (Duraklama Dönemi) (1595 - 1699)",
                            OrderIndex = 7,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 43,
                            LessonId = 4,
                            Name = "XVIII. Yüzyılda Osmanlı Devleti (Gerileme Dönemi) (1699 - 1792)",
                            OrderIndex = 8,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 44,
                            LessonId = 4,
                            Name = "XIX. Yüzyılda Osmanlı Devleti (Dağılma Dönemi) (1792 - 1922)",
                            OrderIndex = 9,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 45,
                            LessonId = 4,
                            Name = "XX. Yüzyıl Başlarında Osmanlı Devleti",
                            OrderIndex = 10,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 46,
                            LessonId = 4,
                            Name = "Mondros Ateşkes Antlaşması ve İlk İşgaller",
                            OrderIndex = 11,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 47,
                            LessonId = 4,
                            Name = "Milli Mücadele Hazırlık Dönemi",
                            OrderIndex = 12,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 48,
                            LessonId = 4,
                            Name = "I. TBMM Dönemi ve Gelişmeleri (1920 - 1923)",
                            OrderIndex = 13,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 49,
                            LessonId = 4,
                            Name = "Milli Mücadele Muharebeler Dönemi",
                            OrderIndex = 14,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 50,
                            LessonId = 4,
                            Name = "Atatürk'ün Hayatı",
                            OrderIndex = 15,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 51,
                            LessonId = 4,
                            Name = "Atatürk Dönemi İç Politika",
                            OrderIndex = 16,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 52,
                            LessonId = 4,
                            Name = "Atatürk İlkeleri",
                            OrderIndex = 17,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 53,
                            LessonId = 4,
                            Name = "Atatürk İnkılapları",
                            OrderIndex = 18,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 54,
                            LessonId = 4,
                            Name = "Atatürk Dönemi Türk Dış Politikası",
                            OrderIndex = 19,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 55,
                            LessonId = 4,
                            Name = "Cumhuriyet Dönemi Kültür ve Medeniyeti",
                            OrderIndex = 20,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 56,
                            LessonId = 4,
                            Name = "XX. Yüzyıl Başlarında Dünya (1918 - 1939)",
                            OrderIndex = 21,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 57,
                            LessonId = 4,
                            Name = "II. Dünya Savaşı (1939 - 1945)",
                            OrderIndex = 22,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 58,
                            LessonId = 4,
                            Name = "Soğuk Savaş Dönemi (1947 - 1990)",
                            OrderIndex = 23,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 59,
                            LessonId = 4,
                            Name = "Yumuşama Dönemi (1961 - 1990)",
                            OrderIndex = 24,
                            Priority = (byte)3
                        },
                        new
                        {
                            Id = 60,
                            LessonId = 4,
                            Name = "Küreselleşen Dünya (1990 - 2026)",
                            OrderIndex = 25,
                            Priority = (byte)3
                        });
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserActivityHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityHistories");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserLessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgressStatus")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLessonProgresses");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowFriendRequests")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyReminderHour")
                        .HasColumnType("int");

                    b.Property<int>("DailyStudyMinuteGoal")
                        .HasColumnType("int");

                    b.Property<bool>("IsProfilePublic")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowRankInLeaderboard")
                        .HasColumnType("bit");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WeeklyQuestionGoal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserQuestionStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalSolvedCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimeSpentInMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuestionStats");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserWeeklyGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentQuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStudyMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TargetQuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("TargetStudyMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("UserWeeklyGoals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "Requestor")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Exam", "Exam")
                        .WithMany("Lessons")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.LessonSchedule", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("LessonSchedule")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Mock.UserMockExam", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("MockExams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Mock.UserMockExamDetail", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Mock.UserMockExam", "UserMockExam")
                        .WithMany("Details")
                        .HasForeignKey("UserMockExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("UserMockExam");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.ProfileStat", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithOne("ProfileStat")
                        .HasForeignKey("StudyVera.Domain.Entities.ProfileStat", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.QuestionStatDetail", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.UserQuestionStat", "userQuestionStat")
                        .WithMany("QuestionStatDetails")
                        .HasForeignKey("UserQuestionStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userQuestionStat");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.StudySession", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("StudyVera.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Topic", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Topics")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserActivityHistory", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("UserActivityHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserLessonProgress", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("StudyVera.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserQuestionStat", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", "User")
                        .WithMany("QuestionStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserWeeklyGoal", b =>
                {
                    b.HasOne("StudyVera.Domain.Entities.Identity.AppUser", null)
                        .WithMany("UserWeeklyGoals")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Navigation("LessonProgresses");

                    b.Navigation("LessonSchedule");

                    b.Navigation("MockExams");

                    b.Navigation("ProfileStat");

                    b.Navigation("QuestionStats");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserActivityHistories");

                    b.Navigation("UserSettings");

                    b.Navigation("UserWeeklyGoals");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.Mock.UserMockExam", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("StudyVera.Domain.Entities.UserQuestionStat", b =>
                {
                    b.Navigation("QuestionStatDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
